name: Release Upload Mod

on:
  release:
    types: [published]

permissions: write-all

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Zip Mod
        run: zip -r autobello_kart.zip . -x '*.git*'
      - name: Add mod zip to release
        uses: softprops/action-gh-release@v1
        with:
          files: autobello_kart.zip
